% setup_training.m
function options = setup_training(doValidation)
    options = trainingOptions('adam', ...
        ... % Optimization parameters
        'InitialLearnRate', 0.001, ...
        'LearnRateSchedule', 'piecewise', ...
        'LearnRateDropFactor', 0.1, ...
        'LearnRateDropPeriod', 20, ...
        'MaxEpochs', 100, ...
        'MiniBatchSize', 128, ...
        'GradientThreshold', 1, ...
        'L2Regularization', 0.0001, ...
        ... % Hardware acceleration
        'ExecutionEnvironment', 'parallel', ... % Use parallel computing
        'WorkerLoad', 0.8, ...                 % Use 80% of available workers
        ... % Validation parameters
        'ValidationFrequency', 50, ...
        'ValidationPatience', 8, ...
        ... % Display and plotting parameters
        'Verbose', true, ...
        'VerboseFrequency', 50, ...
        'Plots', 'training-progress', ...
        'Shuffle', 'every-epoch');
        
    if ~doValidation
        options.ValidationData = [];
        options.ValidationFrequency = [];
        options.ValidationPatience = [];
    end
end